version: '3'

services:
  phalcon-mailer-8.0:
    build: docker/8.0
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailhog

  phalcon-mailer-8.1:
    build: docker/8.1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025