version: '3'

services:
  phalcon-mailer-7.4:
    build: docker/7.4
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  phalcon-mailer-8.0:
    build: docker/8.0
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  phalcon-mailer-8.1:
    build: docker/8.1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - ./tests/_data/smtp-authentication:/smtp-authentication
    command: --smtp-auth-allow-insecure --smtp-auth-file /smtp-authentication

  mailpit-sendmail:
    image: axllent/mailpit
    ports:
      - 1026:1025
      - 8026:8025
    command: --smtp=0.0.0.0:1026 --listen=0.0.0.0:8026