version: '3'

services:
  phalcon-mailer-8.0:
    build: docker/8.0
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailhog
      - mailhog-fail-recipients

  phalcon-mailer-8.1:
    build: docker/8.1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailhog
      - mailhog-fail-recipients

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

  # Testing the failed recipients
  mailhog-fail-recipients:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1026:1025
      - 8026:8025
    command: -invite-jim -jim-reject-recipient=1 -jim-reject-sender=0 -jim-reject-auth=0 -jim-disconnect=0 -jim-accept=1
