version: '3'

services:
  phalcon-mailer-7.4:
    build: docker/7.4
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  phalcon-mailer-8.0:
    build: docker/8.0
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  phalcon-mailer-8.1:
    build: docker/8.1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - ./tests/_data/smtp-authentication:/smtp-authentication
    environment:
      MP_SMTP_AUTH_FILE: /smtp-authentication
      MP_SMTP_AUTH_ALLOW_INSECURE: true

  mailpit-sendmail:
    image: axllent/mailpit
    ports:
      - 1026:1026
      - 8026:8026
    environment:
      MP_SMTP_BIND_ADDR: 0.0.0.0:1026
      MP_UI_BIND_ADDR: 0.0.0.0:8026